export const FETCH_TRANSACTION_BY_CUSTOMER_ID =
  "FETCH_TRANSACTION_BY_CUSTOMER_ID";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_PRODUCT_BY_PRODUCT_ID = "FETCH_PRODUCT_BY_PRODUCT_ID";
export const FETCH_STATES = "FETCH_STATES";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_ACCOUNTS_BY_CUSTOMER_ID = "FETCH_ACCOUNTS_BY_CUSTOMER_ID";
export const FETCH_USER_BY_CUSTOMER_ID = "FETCH_USER_BY_CUSTOMER_ID";
export const FETCH_ACCOUNT_BY_ACCOUNT_ID = "FETCH_ACCOUNT_BY_ACCOUNT_ID";
export const FETCH_INVESTMENTS_BY_CUSTOMER_ID =
  "FETCH_INVESTMENTS_BY_CUSTOMER_ID";
export const FETCH_BANKS = "FETCH_BANKS";
export const FETCH_DASHBOARD_DATA = "FETCH_DASHBOARD_DATA";
export const FETCH_ACCOUNTS_WITH_FILTER = "FETCH_ACCOUNTS_WITH_FILTER";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ADMIN_USER_BY_USERNAME = "FETCH_ADMIN_USER_BY_USERNAME";
