export const FETCH_TRANSACTION_BY_CUSTOMER_ID =
  "FETCH_TRANSACTION_BY_CUSTOMER_ID";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_PRODUCT_BY_PRODUCT_ID = "FETCH_PRODUCT_BY_PRODUCT_ID";
